============================= test session starts =============================
platform win32 -- Python 3.4.3 -- py-1.4.26 -- pytest-2.6.4
collected 0 items / 1 errors

=================================== ERRORS ====================================
_________________________ ERROR collecting test_1.py __________________________
test_1.py:12: in <module>
    from label_csv import test_label_csv1, test_default_dicts, test_segment_specs, test_label_csv2
E   ImportError: cannot import name 'test_default_dicts'
=========================== 1 error in 0.39 seconds ===========================
